routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Index Route
Route::get('/', function () { return redirect()->route('dashboard.index'); })->name('index');

Route::group(['prefix' => 'admin', 'namespace' => 'Admin'], function () {
    // Authenticate routes
    Route::group(['prefix' => 'auth'], function () {
        Route::get('login', 'AuthController@showLoginForm')->name('login');
        Route::post('login', 'AuthController@login');
        Route::get('logout', 'AuthController@logout')->name('logout');
    });

    // Application routes
    Route::group(['middleware' => 'auth'], function () {
        // Dashboard (home page)
        Route::get('dashboard', 'DashboardController@index')->name('dashboard.index');
        // Resource Routes
        Route::resource('publishers', 'PublisherController', ['except' => ['edit']]);
        Route::resource('players', 'PlayerController', ['except' => ['show']]);
        Route::resource('sessions', 'SessionController', ['except' => ['show']]);
        Route::resource('users', 'UserController', ['except' => ['show']]);
    });
});

Route::get('player/{name}', 'MediaController@getEmbeddedPlayer')->name('media.player');
Route::post('media/callback/publish', 'MediaController@onPublish')->name('media.callback.publish');

app/Publisher.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Publisher extends Model
{
    /**
     * The attributes that aren't mass assignable.
     *
     * @var array
     */
    protected $guarded = [];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'secret'
    ];

    /**
     * Morph To (reverse).
     * @return \Illuminate\Database\Eloquent\Relations\MorphTo
     */
    public function source()
    {
        return $this->morphTo();
    }

    /**
     * Related to all sessions.
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function sessions()
    {
        return $this->hasMany(Session::class);
    }

    /**
     * Related to current session.
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function live_session()
    {
        return $this->belongsTo(Session::class, 'current_session', 'id');
    }

    /**
     * Related to all players of this publisher.
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function players()
    {
       return $this->hasMany(Player::class);
    }

    /**
     * Get target of this publisher (source's target)
     */
    public function getTarget()
    {
        switch ($this->source_type) {
            case Car::class: return $this->source->car_id;
            case Desktop::class: return $this->source->name;
            default: return null;
        }
    }
}

app/Http/Controllers/Admin/PublisherController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Car;
use App\Desktop;
use App\Http\Controllers\Controller;
use App\Publisher;
use Illuminate\Http\Request;

class PublisherController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @param Request $request
     * @return \Illuminate\Http\Response
     * @throws \Exception
     */
    public function index(Request $request)
    {
        if ($request->ajax()) {
            return datatables()
                ->eloquent(Publisher::query()->with('source'))
                ->editColumn('source_type', function (Publisher $publisher) {
                    $source = $publisher->source;
                    if ($source instanceof Car) {
                        return 'Car';
                    } else {
                        return 'Desktop';
                    }
                })
                ->addColumn('target', function (Publisher $publisher) {
                    return $publisher->getTarget();
                })
                ->addColumn('live', function (Publisher $publisher) {
                    if (is_null($publisher->live_session)) {
                        return '<span class="label label-live label-default">no</span>';
                    } else {
                        return '<a href="'.route('sessions.edit', ['session' => $publisher->live_session->id]).'"><span class="label label-danger">live</span></a>';
                    }
                })
                ->addColumn('action', function (Publisher $publisher) {
                    return '<button class="btn btn-primary btn-view-modal" onclick="openViewModal('.$publisher->id.')">Show Details</a>';
                })
                ->rawColumns(['live', 'action'])
                ->toJson();
        }

        $table = datatables()->getHtmlBuilder()->columns([
            ['data' => 'id', 'title' => '#'],
            ['data' => 'source_type', 'title' => 'Type'],
            ['data' => 'target', 'title' => 'Target', 'sortable' => false, 'orderable' => false],
            ['data' => 'token', 'title' => 'Token'],
            ['data' => 'live', 'title' => 'Live Status'],
            ['data' => 'created_at', 'title' => 'Created At'],
            ['data' => 'updated_at', 'title' => 'Updated At'],
            ['data' => 'action', 'title' => 'Action', 'orderable' => false, 'searchable' => false]
        ]);

        return view('publishers.index', compact('table'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // Validate input
        $this->validate($request, [
            'type' => 'required|string|max:255|in:Car,Desktop',
            'target' => 'required|string|max:255',
        ]);

        // Create Publisher
        $publisher = new Publisher([
            'token' => $this->generateToken(),
            'secret' => $this->generateToken(),
        ]);
        // Associate source type
        $associateModel = null;
        switch ($request->get('type')) {
            case 'Car': {
                $associateModel = Car::create([
                    'car_id' => $request->get('target'),
                ]);
            } break;
            case 'Desktop': {
                $associateModel = Desktop::create([
                    'name' => $request->get('target'),
                ]);
            } break;
        }
        $publisher->source()->associate($associateModel);
        $publisher->save();

        return redirect()
            ->back()
            ->success(__('publishers.created'));
    }

    /**
     * Display the specified resource.
     *
     * @param Publisher $publisher
     * @return \Illuminate\Http\Response
     */
    public function show(Publisher $publisher)
    {
        return view('publishers.view-fragment', compact('publisher'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    protected function generateToken($length = 32)
    {
        $chars = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXTZabcdefghiklmnopqrstuvwxyz!@#$^_";
        $result = '';

        for ($ignored = 0; $ignored < $length; $ignored++) {
            $rNum = rand(0, strlen($chars));
            $result .= substr($chars, $rNum, 1);
        }

        return $result;
    }
}

resources/views/publishers/create-fragment.blade.php
<div class="row">
    <div class="col-xs-12">
        <div class="box">
            <div class="box-header with-border">
                <h3 class="box-title">Add Publisher</h3>
            </div>
            <!-- /.box-header -->
            <!-- form start -->
            <form action="{{ route('publishers.store') }}" method="post" class="form-horizontal" autocomplete="off">
                @csrf

                <input type="hidden" autocomplete="false">

                <div class="box-body">
                    <div class="form-group">
                        <label for="type" class="col-sm-2 control-label">Type</label>

                        <div class="col-sm-10">
                            <select class="form-control" name="type" id="type">
                                <option value="" selected disabled>Please select type</option>
                                <option value="Car">Car</option>
                                <option value="Desktop">Desktop</option>
                            </select>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="target" id="target-label" class="col-sm-2 control-label">Target</label>

                        <div class="col-sm-10">
                            <input type="text" class="form-control" name="target" id="target" required disabled>
                        </div>
                    </div>
                </div>

                <!-- /.box-body -->
                <div class="box-footer">
                    <button type="submit" class="btn btn-success pull-right">Add Publisher</button>
                </div>
                <!-- /.box-footer -->
            </form>
        </div>
        <!-- /.box -->
    </div>
</div>

resources/views/publishers/css-helper.blade.php
<style>
    .label-live {
        font-size: 1.25rem;
    }

    .btn-live, .label-live-form {
        display: block;
        width: 100%;
        height: 34px;
        padding: 6px 12px;
        font-size: 1.75rem;
        font-weight: bold;
        line-height: 1.228571;
    }
</style>

resources/views/publishers/index.blade.php
@extends('layouts.main')

@section('styles')
    @include('vendors.datatables.css')
    @include('publishers.css-helper')
    <style>
        textarea {
            resize: none;
        }
    </style>
@endsection

@section('header')
    <h1>
        Publishers
    </h1>
@endsection

@section('body')

    @include('publishers.create-fragment')

    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header with-border">
                    <h3 class="box-title">Publisher list</h3>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    {!! $table->table() !!}
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade in" id="modal-view">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span></button>
                    <h4 class="modal-title">Publisher Details: <span id="modal-view-id"></span></h4>
                </div>
                <div class="modal-body" id="modal-view-body"></div>
                <div class="modal-footer">
                    <button type="button" class="btn pull-right" data-dismiss="modal">Cancel</button>
                </div>
            </div>
            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
    </div>
@endsection

@section('scripts')
    @include('vendors.datatables.js')
    @include('components.js-helper')
    @include('publishers.js-helper')
    {!! $table->scripts() !!}

    <script type="text/javascript">
        function openViewModal(id) {
            let buttons = $('.btn-view-modal');
            buttons.html('Loading...');
            buttons.attr('disabled', true);

            $.get(`{{ url('admin/publishers/') }}/${id}`)
                .done(function(data) {
                    $('#modal-view-id').html(id);
                    $('#modal-view-body').html(data);
                    $('#modal-view').modal('toggle');
                })
                .always(function() {
                    buttons.html('Show Details');
                    buttons.attr('disabled', false);
                });
        }
    </script>
@endsection

resources/views/publishers/js-helper.blade.php
<script>
    $('#type').change(function () {
        let label = $('#target-label');
        let target = $('#target');
        switch ($(this).val()) {
            case 'Car': {
                label.html('Car ID');
            } break;
            case 'Desktop': {
                label.html('Desktop Name');
            } break;
        }
        target.attr('disabled', false);
        target.val('');
    });
</script>

resources/views/publishers/view-fragment.blade.php
<form class="form-horizontal" onsubmit="((e) => e.preventDefault())()">

    <div class="box-body">
        <div class="form-group">
            <label for="v_id" class="col-sm-2 control-label">Id</label>

            <div class="col-sm-10">
                <input type="text" class="form-control" name="v_id" id="v_id" value="{{ $publisher->id }}" readonly>
            </div>
        </div>

        <div class="form-group">
            <label for="v_secret" class="col-sm-2 control-label">Type</label>

            <div class="col-sm-10">
                <input type="text" class="form-control" name="v_secret" id="v_secret" value="{{ $publisher->secret }}" readonly>
            </div>
        </div>

        @if($publisher->source instanceof \App\Car)
            <div class="form-group">
                <label for="v_target" class="col-sm-2 control-label">Car ID</label>

                <div class="col-sm-10">
                    <input type="text" class="form-control" name="v_target" id="v_target" value="{{ $publisher->source->car_id }}" readonly>
                </div>
            </div>
        @elseif($publisher->source instanceof \App\Desktop)
            <div class="form-group">
                <label for="v_target" class="col-sm-2 control-label">Desktop Name</label>

                <div class="col-sm-10">
                    <input type="text" class="form-control" name="v_target" id="v_target" value="{{ $publisher->source->name }}" readonly>
                </div>
            </div>
        @endif

        <div class="form-group">
            <label for="v_token" class="col-sm-2 control-label">Token</label>

            <div class="col-sm-10">
                <input type="text" class="form-control" name="v_token" id="v_token" value="{{ $publisher->token }}" readonly>
            </div>
        </div>

        <div class="form-group">
            <label for="v_secret" class="col-sm-2 control-label">Secret</label>

            <div class="col-sm-10">
                <input type="text" class="form-control" name="v_secret" id="v_secret" value="{{ $publisher->secret }}" readonly>
            </div>
        </div>

        <div class="form-group">
            <label for="secret" class="col-sm-2 control-label">Is Currently Live</label>

            <div class="col-sm-10">
                @if (is_null($publisher->live_session))
                    <span class="label label-live-form label-default">no</span>
                @else
                    <a href="{{ route('sessions.edit', ['session' => $publisher->live_session->id]) }}"
                       class="btn btn-danger btn-live">live</a>
                @endif
            </div>
        </div>
    </div>

</form>
<hr />
<h3>To start live streaming</h3>
<form class="form-horizontal" onsubmit="((e) => e.preventDefault())()">
    <div class="box-body">
        <div class="form-group">
            <label for="rtmp_root" class="col-sm-2 control-label">RTMP Root</label>

            <div class="col-sm-10">
                <input type="text" class="form-control" id="rtmp_root" value="rtmp://35.197.157.192/surveillance" readonly>
            </div>
        </div>

        <div class="form-group" style="margin-bottom: 0px;">
            <label for="stream_name" class="col-sm-2 control-label">Stream Name</label>

            <div class="col-sm-10">
                <input type="text" class="form-control" id="stream_name" value="{{ $publisher->getTarget() }}" readonly>
            </div>
        </div>

        <h4 class="col-sm-12 control-label" style="margin-bottom: 1.85rem; text-align: center; font-weight: bold;">Parameters</h4>

        <div class="form-group">
            <label for="p_token" class="col-sm-2 control-label">token</label>

            <div class="col-sm-10">
                <input type="text" class="form-control" id="p_token" value="{{ $publisher->token }}" readonly>
            </div>
        </div>

        <div class="form-group" style="margin-bottom: 0px;">
            <label for="p_secret" class="col-sm-2 control-label">secret</label>

            <div class="col-sm-10">
                <input type="text" class="form-control" id="p_secret" value="{{ $publisher->secret }}" readonly>
            </div>
        </div>
    </div>
</form>
<h5>Video will available at: <a href="{{ route('media.player', ['name' => $publisher->getTarget()]) }}" target="_blank">{{ route('media.player', ['name' => $publisher->getTarget()]) }}</a></h5>
<hr />
<h3>Streaming Configuration Presets</h3>
<hr />
<h4><b>OBS</b></h4>
<p>Set stream type to <code>Custom Streaming Server</code> and set the configurations as below.</p>
<form onsubmit="((e) => e.preventDefault())()">
    <div class="form-group">
        <label for="obs_url" class="control-label">URL</label>
        <input type="text" class="form-control" id="obs_url" value="rtmp://35.197.157.192/surveillance" readonly />
    </div>
    <div class="form-group">
        <label for="obs_stream_key" class="control-label">Steam key</label>
        <textarea class="form-control" id="obs_stream_key" readonly>{{ $publisher->getTarget() }}?token={{ $publisher->token }}&secret={{ $publisher->secret }}</textarea>
    </div>
</form>
<hr />
<h4><b>FFmpeg</b></h4>
<p>Copy these path for live streaming.</p>
<form onsubmit="((e) => e.preventDefault())()">
    <div class="form-group">
        <label for="obs_stream_key" class="control-label">Full Path</label>
        <textarea class="form-control" id="obs_stream_key" readonly>rtmp://35.197.157.192/surveillance/{{ $publisher->getTarget() }}?token={{ $publisher->token }}&secret={{ $publisher->secret }}</textarea>
    </div>
</form>